-- MySQL Script generated by MySQL Workbench
-- 02/16/16 21:50:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema data_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `data_test` ;
CREATE SCHEMA IF NOT EXISTS `data_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `data_test` ;

-- -----------------------------------------------------
-- Table `data_test`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_test`.`users` ;

CREATE TABLE IF NOT EXISTS `data_test`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_domain` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_test`.`invoices` ;

CREATE TABLE IF NOT EXISTS `data_test`.`invoices` (
  `idinvoices` INT NOT NULL AUTO_INCREMENT,
  `idusers` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`idinvoices`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
